version: '3.8'
services:
  chroniclequill:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    depends_on:
      - redis
      - rabbitmq
      - postgres
    entrypoint: ['./entrypoint.sh']
    container_name: chroniclequill
  postgres:
    image: postgres:latest 
    container_name: postgres_container  # Optional, name for the container
    ports:
      - "5431:5432"  # Maps container port 5432 to your local port 5431
    env_file:
      - dev.env  # File containing environment variables like POSTGRES_USER, POSTGRES_PASSWORD, etc.
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage volume for PostgreSQL data
    restart: unless-stopped  # Automatically restarts the container if stopped
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: my-rabbitmq
    env_file:
      - dev.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"  # Redis default port
    volumes:
      - redis_data:/data  # Persistent storage volume for Redis data
    restart: unless-stopped  # Automatically restart Redis if stopped

volumes:
  rabbitmq_data:
  rabbitmq_log:
  postgres_data:
    driver: local
  redis_data:
    driver: local
