# Generated by Django 4.1.13 on 2024-10-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], default='INFO', max_length=10)),
                ('event_type', models.CharField(choices=[('USER_ACTION', 'User Action'), ('SYSTEM_EVENT', 'System Event'), ('AUTH_EVENT', 'Authentication Event'), ('TASK_EVENT', 'Task Event')], default='SYSTEM_EVENT', max_length=20)),
                ('message', models.TextField()),
                ('service_name', models.CharField(max_length=100)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['level'], name='logger_log_level_41f1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['event_type'], name='logger_log_event_t_9b8825_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['timestamp'], name='logger_log_timesta_f6598d_idx'),
        ),
    ]
